from tikon.ecs.aprioris import APrioriDens

from tikon.móds.rae.orgs.ecs.utils import ECS_TRANS, ECS_MRTE, ECS_ESTOC, ECS_DEPR, ECS_REPR

a_prioris = {
    'A. astur': [
        dict(stage='huevo',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((2, 3), 0.80),
             ),
        dict(stage='huevo',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80),
             ),
        dict(stage='huevo',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.03, 0.10), 0.8)
             ),
        dict(stage='huevo',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.005), 1)),
        dict(stage='juvenil 1',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.01, 0.02), 0.8)
             ),
        dict(stage='juvenil 1',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((3, 4), 0.80),
             ),
        dict(stage='juvenil 1',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80),
             ),
        dict(stage='juvenil 1',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.005), 1)),
        dict(stage='juvenil 2',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.01, 0.02), 0.8),
             ),
        dict(stage='juvenil 2',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((4, 6), 0.80),
             ),
        dict(stage='juvenil 2',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80)),
        dict(stage='juvenil 2',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.005), 1)),
        dict(stage='juvenil 3',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.01, 0.02), 0.8)),
        dict(stage='juvenil 3',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((5, 7), 0.80)),
        dict(stage='juvenil 3',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80)),
        dict(stage='juvenil 3',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.005), 1)),
        dict(stage='pupa',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.005), 1)),
        dict(stage='pupa',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((8, 10), 0.80)),
        dict(stage='pupa',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80)),
        dict(stage='pupa',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.02, 0.04), 0.8)),
        dict(stage='adulto',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((12, 18), 0.80)),
        dict(stage='adulto',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((1, 3), 0.80)),
        dict(stage='adulto',
             categ=ECS_REPR, sub_categ='Prob', ec='Normal', prm='n',
             apriori=APrioriDens((85, 100), 0.80)),
        dict(stage='adulto',
             categ=ECS_REPR, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((8, 12), 0.80)),
        dict(stage='adulto',
             categ=ECS_REPR, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((3, 5), 0.80)),
        dict(stage='adulto',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.05), 1.0)),
        dict(stage='adulto',
             categ=ECS_DEPR, sub_categ='Ecuación', ec='Kovai', prm='a',
             apriori=APrioriDens((0.14, 0.15), 0.80)),
        dict(stage='adulto',
             categ=ECS_DEPR, sub_categ='Ecuación', ec='Kovai', prm='b',
             apriori=APrioriDens((150, 300), 0.80)),
    ],

    "M. boniensis": [
        dict(stage='huevo',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((2, 4), 0.80),
             ),
        dict(stage='huevo',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80),
             ),
        dict(stage='huevo',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.03, 0.10), 0.8)
             ),
        dict(stage='huevo',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.005), 1)),
        dict(stage='juvenil 1',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.01, 0.02), 0.8)
             ),
        dict(stage='juvenil 1',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((2, 3), 0.80),
             ),
        dict(stage='juvenil 1',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80),
             ),
        dict(stage='juvenil 1',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.005), 1)),
        dict(stage='juvenil 2',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.01, 0.02), 0.8),
             ),
        dict(stage='juvenil 2',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((4, 5), 0.80),
             ),
        dict(stage='juvenil 2',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80)),
        dict(stage='juvenil 2',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.005), 1)),
        dict(stage='juvenil 3',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.01, 0.02), 0.8)),
        dict(stage='juvenil 3',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((4, 6), 0.80)),
        dict(stage='juvenil 3',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80)),
        dict(stage='juvenil 3',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.005), 1)),
        dict(stage='pupa',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.005), 1)),
        dict(stage='pupa',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((6, 8), 0.80)),
        dict(stage='pupa',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80)),
        dict(stage='pupa',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.02, 0.04), 0.8)),
        dict(stage='adulto',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((17, 22), 0.80)),
        dict(stage='adulto',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((1, 3), 0.80)),
        dict(stage='adulto',
             categ=ECS_REPR, sub_categ='Prob', ec='Normal', prm='n',
             apriori=APrioriDens((110, 125), 0.80)),
        dict(stage='adulto',
             categ=ECS_REPR, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((8, 12), 0.80)),
        dict(stage='adulto',
             categ=ECS_REPR, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((3, 5), 0.80)),
        dict(stage='adulto',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.05), 1.0)),
        dict(stage='adulto',
             categ=ECS_DEPR, sub_categ='Ecuación', ec='Kovai', prm='a',
             apriori=APrioriDens((0.14, 0.15), 0.80)),
        dict(stage='adulto',
             categ=ECS_DEPR, sub_categ='Ecuación', ec='Kovai', prm='b',
             apriori=APrioriDens((150, 300), 0.80)),
    ],

    'A. rugioperculatus': [
        dict(stage='huevo',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((4, 7), 0.80)),
        dict(stage='huevo',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80)),
        dict(stage='huevo',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0, 0.005), 0.8)),
        dict(stage='huevo',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),

        dict(stage='juvenil 1',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((6, 8), 0.80)),
        dict(stage='juvenil 1',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80)),
        dict(stage='juvenil 1',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0, 0.005), 0.8)),
        dict(stage='juvenil 1',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),

        dict(stage='juvenil 2',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((5, 6), 0.80)),
        dict(stage='juvenil 2',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80)),
        dict(stage='juvenil 2',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0, 0.005), 0.8)),
        dict(stage='juvenil 2',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),

        dict(stage='juvenil 3',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((8, 9), 0.80)),
        dict(stage='juvenil 3',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80)),
        dict(stage='juvenil 3',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0, 0.005), 0.8)),
        dict(stage='juvenil 3',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),

        dict(stage='pupa',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((10, 11), 0.80)),
        dict(stage='pupa',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80)),
        dict(stage='pupa',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0, 0.005), 0.8)),
        dict(stage='pupa',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),

        dict(stage='adulto',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),
        dict(stage='adulto',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((20, 24), 0.80)),
        dict(stage='adulto',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((3, 4), 0.80)),
        dict(stage='adulto',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0, 0.01), 0.8)),
        dict(stage='adulto',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),
    ],

    'P. bondari': [
        dict(stage='huevo',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((7, 8), 0.80)),
        dict(stage='huevo',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80)),
        dict(stage='huevo',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0, 0.005), 0.8)),
        dict(stage='huevo',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),

        dict(stage='juvenil 1',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((3, 4), 0.80)),
        dict(stage='juvenil 1',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80)),
        dict(stage='juvenil 1',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0, 0.005), 0.8)),
        dict(stage='juvenil 1',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),

        dict(stage='juvenil 2',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((7, 8), 0.80)),
        dict(stage='juvenil 2',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80)),
        dict(stage='juvenil 2',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0, 0.005), 0.8)),
        dict(stage='juvenil 2',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),

        dict(stage='juvenil 3',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((7, 8), 0.80)),
        dict(stage='juvenil 3',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80)),
        dict(stage='juvenil 3',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0, 0.005), 0.8)),
        dict(stage='juvenil 3',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),

        dict(stage='pupa',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((4, 5), 0.80)),
        dict(stage='pupa',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((0.5, 1), 0.80)),
        dict(stage='pupa',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0, 0.005), 0.8)),
        dict(stage='pupa',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),

        dict(stage='adulto',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),
        dict(stage='adulto',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((15, 16), 0.80)),
        dict(stage='adulto',
             categ=ECS_TRANS, sub_categ='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((1, 2), 0.80)),
        dict(stage='adulto',
             categ=ECS_MRTE, sub_categ='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0, 0.01), 0.8)),
        dict(stage='adulto',
             categ=ECS_ESTOC, sub_categ='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),
    ]
}
